// vuejs/src/components/PlayerEditDialog.vue
<template>
  <md-dialog :md-active.sync="value" :md-close-on-esc="false" :md-click-outside-to-close="false"
    @md-opened="open">
  <md-dialog-content>
    
    <div style="padding-bottom: 20px;">
      <div style="display:inline-block; font-size: 1.5em; margin-top: 0.5em;">
      Edit Player
      </div>
      <span style="float:right;">
        <md-button class="md-raised" :disabled="($v.$invalid || !$v.$anyDirty)" @click="update()">Update</md-button>
        <md-button class="md-raised md-accent" @click="close()">Cancel</md-button>
      </span>
    </div>

    <div class="md-layout md-gutter">
      <div class="md-layout-item half-width">
        <md-field>
          <label>Name</label>
          <md-input placeholder="Name" v-model="$v.player.Name.$model" required md-dense />
        </md-field>
        <div class="error" v-if="!$v.player.Name.required">Field is required</div>
        <div class="error" v-if="!$v.player.Name.minLength">Name must have at least {{$v.player.Name.$params.minLength.min}} letters.</div>
      </div>  

      <div class="md-layout-item half-width">  
        <md-field>
          <label>Country</label>
          <md-select placeholder="Country" v-model="$v.player.CountryId.$model" required md-dense >
            <md-option v-for="item in countries" :key="item.Id" :value="item.Id">{{item.Name}}</md-option>
          </md-select>
        </md-field>
      </div>
    </div>

    <div class="md-layout md-gutter">
      <div class="md-layout-item half-width">
        <md-field>
           <label>Handed</label>
           <md-select placeholder="Handed" v-model="$v.player.Handed.$model">
                <md-option></md-option>
                <md-option value="L">Left</md-option>
                <md-option value="R">Right</md-option>
            </md-select>
        </md-field>
      </div>

      <div class="md-layout-item half-width">
        <md-field>
          <label>Home town</label>
          <md-input placeholder="Home town" v-model="$v.player.HomeTown.$model" md-dense />
        </md-field>
      </div>  
    </div>

    <div class="md-layout md-gutter">
      <div class="md-layout-item half-width">
        <md-datepicker v-model="$v.player.DobDMY.$model" md-immediately md-dense>
        <label>Date of birth</label>
          </md-datepicker>
      </div>  

      <div class="md-layout-item half-width">
        <md-field>
           <label>Gender</label>
           <md-select placeholder="Gender" v-model="$v.player.Gender.$model" required>
                <md-option value=""></md-option>
                <md-option value="F">Female</md-option>
                <md-option value="M">Male</md-option>
            </md-select>
        </md-field>
        <div class="error" v-if="!$v.player.Gender.required">Field is required</div>
      </div>
    </div>

    <div class="md-layout md-gutter">
      <div class="md-layout-item quarter-width">
        <md-field>
          <label>Height feet</label>
          <md-input placeholder="Height feet" v-model.number="$v.player.HeightFeet.$model" type="number" min="4" max="8" size="5" md-dense />
        </md-field>
      </div>  

      <div class="md-layout-item quarter-width">
        <md-field>
          <label>inches</label>
          <md-input placeholder="inches" v-model.number="$v.player.HeightInches.$model" type="number" min="0" max="11" size="5" md-dense />
        </md-field>
      </div>  

      <div class="md-layout-item quarter-width">
        <md-field>
          <label>Weight lbs</label>
          <md-input placeholder="Weight lbs" v-model.number="$v.player.Weight.$model" type="number" size="5" md-dense />
        </md-field>
      </div>  

      <div class="md-layout-item quarter-width">  
        <md-field>
          <label>Turned pro</label>
          <md-select placeholder="Turned pro" v-model="$v.player.TurnedPro.$model" required md-dense >
            <md-option v-for="item in turnedProYears" :key="item" :value="item">{{item}}</md-option>
          </md-select>
        </md-field>
      </div>

    </div>

    <img v-if="$v.player.Photo.$model != null" :src="'data:image/jpeg;base64,' + $v.player.Photo.$model" 
       style="height: 170px;"/>

    <file-upload-dd v-on:fileReceived="fileReceived"></file-upload-dd>
    </md-dialog-content>
  </md-dialog>
</template>

<script>
import DataMixin from "../mixins/data-mixin";
import FileUploadDD from "./FileUploadDD";
import { validationMixin } from 'vuelidate'
import { required, minLength, between } from 'vuelidate/lib/validators'


export default {
  name: 'PlayerEditDialog',
  components: {
    'file-upload-dd': FileUploadDD
  },
  props: {
      value: {
        required: true
      },
      playerId: {
        required: true
      }
  },
  mixins: [DataMixin, validationMixin],
  data() {
    return {
      player: {
        Name: "Bert Ford",
        CountryId: 2
      }
    }
  },
  validations: {
    player: {
      Name: {
        required,
        minLength: minLength(3)
      },
      CountryId: {},
      Handed: {},
      HomeTown: {},
      DobDMY: {},
      Gender: {
        required,
      },
      HeightFeet: {},
      HeightInches: {},
      Weight: {},
      TurnedPro: {
        between: between(1981, 2020)
      },
      Photo: {},
    }
  },
  methods: {
    close() {
      console.log("close()");
      console.log("$v.$anyDirty=" + this.$v.$anyDirty);
      //debugger;
      this.clearForm();
      this.$emit("input", !this.value);
    },
    update() {
      console.log("update()");
      this.updatePlayer(this.playerId, this.player).then(
        res => {
          //this.toastr.info("Record updated");
          res;
          this.clearForm();
          this.$toastr.s("Record updated");
          this.$parent.refreshList();
          this.$emit("input", !this.value);
        },
        err => {
          this.$toastr.e(this.formatError(err.response.data));
        }
      )
    },
    clearForm() {
      console.log("clearForm()");
      this.player.Name = "";
      this.player.CountryId = 0;
      this.player.Handed = "";
      this.player.HomeTown = "";
      this.player.DobDMY = null;
      this.player.Dob = null;
      this.player.Gender = "";
      this.player.HeightFeet = "";
      this.player.HeightInches = "";
      this.player.Weight  = "";
      this.player.TurnedPro = "";
      this.player.Photo = "";
    },
    open() {
      console.log("open(), playerId=" + this.playerId);
      this.getPlayer(this.playerId)
      .then (() => {
        this.$v.$reset();
        console.log("$v.$anyDirty=" + this.$v.$anyDirty);
      });
    },
    fileReceived(evt) {
      console.log("fileReceived()");
      this.$v.player.Photo.$model = evt;
    }
      
  },

  beforeMount() {
    this.getCountries();
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
/* fix for md-dialog appearing off-centre */
.md-dialog /deep/ .md-dialog-container {
  transform: none;
  width: 500px;
  min-height: 560px;
  padding-top: 0px;
  padding-left: 20px;
  padding-right: 20px;
}

.md-dialog-content {
  margin-top: -10px;
}

.md-button {
  font-weight: bold;
  text-transform: none !important;
}
.half-width {
  max-width: 50%;
  margin-bottom: -15px;
}
.quarter-width {
  max-width: 25%;
}
.error {
  color: #f57f6c;
  font-size: 10px;
  padding: 0;
  margin-top: -25px;
}
</style>
<style>
.md-field.md-focused .md-input,
.md-field.md-focused .md-textarea,
.md-field.md-has-value .md-input,
.md-field.md-has-value .md-textarea,
.md-list-item-container {
  font-size: 14px !important;
}
</style>

// Angular/src/app/player/player-edit-dialog.component.ts
import { Component, Inject, OnInit, Optional, ChangeDetectorRef  } from '@angular/core';
import { FormControl, FormGroup, NgForm } from '@angular/forms';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { Player } from '../models/Player.model';
import { PlayerViewService } from '../shared/player-view.service';
import {MomentDateAdapter, MAT_MOMENT_DATE_ADAPTER_OPTIONS} from '@angular/material-moment-adapter';
import {DateAdapter, MAT_DATE_FORMATS, MAT_DATE_LOCALE} from '@angular/material/core';
// Depending on whether rollup is used, moment needs to be imported differently.
// Since Moment.js doesn't have a default export, we normally need to import using the `* as`
// syntax. However, rollup creates a synthetic default module and we thus need to import it using
// the `default as` syntax.
import * as _moment from 'moment';
// tslint:disable-next-line:no-duplicate-imports
import {default as _rollupMoment} from 'moment';
import { ToastrService } from 'ngx-toastr';

const moment = _rollupMoment || _moment;

// See the Moment.js docs for the meaning of these formats:
// https://momentjs.com/docs/#/displaying/format/
export const MY_FORMATS = {
  parse: {
    dateInput: 'LL',
  },
  display: {
    dateInput: 'LL',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
  },
};

export interface UsersData {
  name: string;
  id: number;
}

@Component({
  selector: 'app-player-edit-dialog',
  templateUrl: './player-edit-dialog.component.html',
  styleUrls: ['./player-edit-dialog.component.css'],
  providers: [
    // `MomentDateAdapter` can be automatically provided by importing `MomentDateModule` in your
    // application's root module. We provide it at the component level here, due to limitations of
    // our example generation script.
    {
      provide: DateAdapter,
      useClass: MomentDateAdapter,
      deps: [MAT_DATE_LOCALE, MAT_MOMENT_DATE_ADAPTER_OPTIONS]
    },

    {provide: MAT_DATE_FORMATS, useValue: MY_FORMATS},
    { provide: MAT_MOMENT_DATE_ADAPTER_OPTIONS, useValue: { useUtc: true } }
  ]
})

export class PlayerEditDialogComponent implements OnInit {

  action : string;
  Id : number;
  player : any = new Player();
  countries : any;
  turnedProYears : number[] = Array.from({length: 40}, (_, i) => i - 40 + new Date().getFullYear());


  constructor(
    public playerViewService : PlayerViewService,
    public playerEditDialog: MatDialogRef<PlayerEditDialogComponent>,
    //@Optional() is used to prevent error if no data is passed
    @Optional() @Inject(MAT_DIALOG_DATA) public data: UsersData,
    private changeDetectorRef:ChangeDetectorRef,
    private toastr : ToastrService) {
    //console.log(data);
    var local_data : any = {...data};
    this.Id = local_data.PlayerId;
    this.action = local_data.action;
  }

  ngOnInit(): void {
    this.playerViewService.getPlayer(this.Id).subscribe(
      res => {
        this.player = res as Player;
        this.playerViewService.getCountries().subscribe(
          res => {
            this.countries = res;
          },
          err => {
            console.log(err);
          }
        );
      },
      err => {
        console.log(err);
      }
    );

  }

  // ChangeDetectorRef stuff removes the ExpressionChangedAfterItHasBeenCheckedError JS error
  ngAfterViewChecked()
  {
      this.changeDetectorRef.detectChanges();
  }

  doAction() {
    this.playerViewService.updatePlayer(this.Id, this.player).subscribe(
      res => {
        this.toastr.info("Record updated");
        this.playerEditDialog.close({event:this.action, data:this.Id});
      },
      err => {
        console.log(err);
        this.toastr.error(this.formatError(err.error));
      }
    );
  }

  closeDialog() {
    this.playerEditDialog.close({event:'Cancel'});
  }

  receiveFileUploaded($event) {
    this.player['Photo'] = $event;
  }

  formIsValid() {
    document.getElementById('Dob').classList.remove('ng-invalid');
    let anyInvalid : Boolean = document.getElementsByClassName('ng-invalid').length > 0;
    if (anyInvalid) {
      return !anyInvalid;
    }
    
    if (this.player.Dob && new Date(this.player.Dob).getFullYear() < 1970) {
      document.getElementById('Dob').classList.add('ng-invalid');
      return false;
    } 

    return true;
  }

  formatError(errorText : string) {
    var idx = errorText.indexOf("Exception: ");
    if (idx > -1) {
      errorText = errorText.substring(idx + "Exception: ".length);
    }
    idx = errorText.indexOf("\r\n   at ");
    if (idx > -1) {
      errorText = errorText.substring(0, idx);
    }

    return errorText;
  }
  
}

<form>
    <h2 mat-dialog-title>Edit Player
        <span style="float:right;">
            <button mat-button [disabled]="!formIsValid()" (click)="doAction()">{{action}}</button>&nbsp;
            <button mat-button (click)="closeDialog()" mat-flat-button color="warn">Cancel</button>
        </span>
    </h2>

    <div>
        <mat-form-field>
            <input matInput placeholder="Name" [(ngModel)]="player.Name" required="true" [ngModelOptions]="{standalone: true}">
        </mat-form-field>

        <mat-form-field>
            <mat-select placeholder="Country" name="Country" [(ngModel)]="player.CountryId" required="true" [ngModelOptions]="{standalone: true}">
                <mat-option></mat-option>
                <mat-option [value]="country.Id" *ngFor="let country of countries">{{ country.Name }}</mat-option>
            </mat-select>
        </mat-form-field>
    </div>

    <div>  
        <mat-form-field>
            <mat-select placeholder="Handed" name="Handed" [(ngModel)]="player.Handed" [ngModelOptions]="{standalone: true}">
                <mat-option></mat-option>
                <mat-option value="L">Left</mat-option>
                <mat-option value="R">Right</mat-option>
            </mat-select>
        </mat-form-field>

        <mat-form-field>
            <input matInput placeholder="Home town" name="HomeTown" [(ngModel)]="player.HomeTown" required="true" [ngModelOptions]="{standalone: true}">
        </mat-form-field>
    </div>

    <div>  
        <mat-form-field style="width:180px !important;">
            <input matInput placeholder="Date of Birth" name="Dob" id="Dob" [matDatepicker]="picker" [(ngModel)]="player.Dob" [ngModelOptions]="{standalone: true}">
            <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
            <mat-datepicker #picker></mat-datepicker>
        </mat-form-field>

        <mat-form-field>
            <mat-select placeholder="Gender" name="Gender" [(ngModel)]="player.Gender" required="true" [ngModelOptions]="{standalone: true}">
                <mat-option></mat-option>
                <mat-option value="F">Female</mat-option>
                <mat-option value="M">Male</mat-option>
            </mat-select>
        </mat-form-field>
    </div>

    <div>  
        <mat-form-field style="width:70px !important;">
            <input matInput placeholder="Height feet" name="HeightFeet" [(ngModel)]="player.HeightFeet" type="number" min="4" max="8" [ngModelOptions]="{standalone: true}">
        </mat-form-field>

        <mat-form-field style="width:70px !important;">
            <input matInput placeholder="inches" name="HeightInches" [(ngModel)]="player.HeightInches" type="number" min="0" max="11" [ngModelOptions]="{standalone: true}">
        </mat-form-field>

        <mat-form-field style="width:70px !important;">
            <input matInput placeholder="Weight lbs" name="Weight" [(ngModel)]="player.Weight" [ngModelOptions]="{standalone: true}">
        </mat-form-field>

        <mat-form-field style="width:70px !important;">
            <mat-select placeholder="Turned Pro" name="TurnedPro" [(ngModel)]="player.TurnedPro" [ngModelOptions]="{standalone: true}">
                <mat-option></mat-option>
                <mat-option [value]="year" *ngFor="let year of turnedProYears">{{ year }}</mat-option>
            </mat-select>
        </mat-form-field>
    </div>

    <img *ngIf="player.Photo != null" src="data:image/jpeg;base64,{{player.Photo}}"/>
    <file-upload-dd (fileUploadedEvent)="receiveFileUploaded($event)" ></file-upload-dd>

</form>
