// vuejs/src/components/PlayerList.vue
<template>
  <div>
    <h2>Tennis Player Rankings (Vue.js)</h2>
    <div class="md-layout md-gutter">
      <div class="md-layout-item smaller-width">
        <md-field>
          <label for="selectGender">Competition </label>
          <md-select id="selectGender" v-model="selectedGender" @md-selected="refreshRankingsList" md-dense >
            <md-option v-for="gender in genders" :key="gender.id" :value="gender.id">{{gender.value}}</md-option>
          </md-select>
        </md-field>
      </div>  
      <div class="md-layout-item smaller-width">  
        <md-field>
          <label for="selectYear">Year </label>
          <md-select id="selectYear" v-model="selectedYear" @md-selected="refreshRankingsList" md-dense >
            <md-option v-for="year in years" :key="year" :value="year">{{year}}</md-option>
          </md-select>
        </md-field>
      </div>
    </div>

    <md-table v-model="rankingsList" md-card md-sort="Rank" md-sort-order="asc">
      <md-table-row slot="md-table-row" slot-scope="{ item }">
        <md-table-cell md-label="Rank" md-sort-by="Rank">{{ item.Rank }}</md-table-cell>
        <md-table-cell md-label="Player's Name">{{ item.PlayerName }}</md-table-cell>
        <md-table-cell md-label="Country" :title="item.CountryName"><img :src="item.CountryImageLink"></md-table-cell>
        <md-table-cell md-label="Points">{{ item.Points }}</md-table-cell>
        <md-table-cell md-label="Prize Money" md-sort-by="PrizeMoney">${{ item.PrizeMoney }}</md-table-cell>
        <md-table-cell md-label="Actions">
          <a href="#" @click="openPlayerEditDialog(item.PlayerId); $event.preventDefault();">Edit Player</a>
        </md-table-cell>
      </md-table-row>
    </md-table>
    <player-edit-dialog v-model="playerEditDialogOpen" :playerId="playerId"></player-edit-dialog>
<!--
    <div v-for="ranking in rankingsList" :key="ranking.Id">
      -{{ranking.PlayerName}}
    </div>
-->    
  </div>
</template>

<script>
import DataMixin from "../mixins/data-mixin";
import PlayerEditDialog from "./PlayerEditDialog";
//import PlayerService from "../services/player-service";

//import { MdField, MdSelect, MdOption } from 'vue-material/dist/components';


export default {
  name: 'PlayerList',
  components: {
    PlayerEditDialog
  },
  props: [],
  mixins: [DataMixin],
  data() {
    return {
      selectedGender: '',
      selectedYear: '',
      genders: [
        {id: 'M', value: 'Men\'s'},
        {id: 'F', value: 'Women\'s'}
      ],
      playerEditDialogOpen: false,
      playerId: 0
    }
  },
  methods: {
    refreshRankingsList() {
      this.getRankingsList(this.selectedYear, this.selectedGender);
    },
    openPlayerEditDialog(playerId) {
      console.log("playerId=" + playerId);
      this.playerId = playerId;
      this.playerEditDialogOpen = false; // needed as need to trigger a change and sometimes value left at true
      this.playerEditDialogOpen = true;
    }    

  },

  beforeMount() {
    this.selectedGender = this.genders[0].id;
    this.getYears().then(() => {
      this.selectedYear = this.years[1];
      this.getRankingsList(this.selectedYear, this.selectedGender);
    });   
  }

}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.smaller-width {
  max-width: 25%;
}

.md-table-cell {
  text-align: left;
}

h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>

// Angular/src/app/player-list/player-list.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { PlayerViewService } from '../shared/player-view.service';
import { PlayerEditDialogComponent } from '../player/player-edit-dialog.component';
import { RankingEditDialogComponent } from '../ranking/ranking-edit-dialog.component';

interface IdValue {
  id: string;
  value: string;
}

@Component({
  selector: 'player-list',
  templateUrl: './player-list.component.html',
  styles: [
    'table {      width: 100%;    }'
  ]
})
export class PlayerListComponent implements OnInit {

  genders: IdValue[] = [];
  selectedGender;
  years : any;
  selectedYear : number;
  rankingList : any;
  rankingListColumns : string[] = ['Rank', 'PlayerName', 'CountryName', 'Points', 'PrizeMoney','Action'];

  constructor(
    public playerViewService : PlayerViewService,
    public dialog: MatDialog
  ) { }

  ngOnInit(): void {
    this.genders = [
      {id: 'M', value: 'Men\'s'},
      {id: 'F', value: 'Women\'s'}
    ];
    this.selectedGender = this.genders[0].id;
  
    this.playerViewService.getYears().subscribe(
      res => {
        this.years = res;
        this.selectedYear = this.years[1]; 
        this.getRankingList(this.selectedYear, this.selectedGender);
      },
      err => {
        console.log(err);
      }
    );
  }

  refreshRankingList() {
    this.getRankingList(this.selectedYear, this.selectedGender);
  }

  getRankingList(year, gender) {
    this.playerViewService.getRankingList(year, gender).subscribe(
      res => {
        this.rankingList = res;
      },
      err => {
        console.log(err);
      }
    );
  }

  openPlayerEditDialog(action, obj) {
    obj.action = action;
    const dialogRef = this.dialog.open(PlayerEditDialogComponent, {
      width: '500px',
      height: '550px',
      data: obj
    });
    
    dialogRef.afterClosed().subscribe(result => {
      this.refreshRankingList();
    });
  }

  openRankingEditDialog(action, obj) {
    obj.action = action;
    const dialogRef = this.dialog.open(RankingEditDialogComponent, {
      width: '500px',
      height: '550px',
      data: obj
    });
    
    dialogRef.afterClosed().subscribe(result => {
      this.refreshRankingList();
    });
  }


}

<mat-form-field appearance="fill">
    <mat-label>Competition</mat-label>
    <mat-select [(value)]="selectedGender" (selectionChange)="refreshRankingList()">
        <mat-option></mat-option>
        <mat-option [value]="option.id" *ngFor="let option of genders">{{ option.value }}</mat-option>
    </mat-select>
</mat-form-field>
<mat-form-field appearance="fill">
    <mat-label>Year</mat-label>
    <mat-select [(value)]="selectedYear" (selectionChange)="refreshRankingList()">
        <mat-option></mat-option>
        <mat-option [value]="year" *ngFor="let year of years">{{ year }}</mat-option>
    </mat-select>
</mat-form-field>

<table mat-table [dataSource]="rankingList" class="mat-elevation-z8">
  <ng-container matColumnDef="Id">
    <th mat-header-cell *matHeaderCellDef> Id </th>
    <td mat-cell *matCellDef="let element"> {{element.Id}} </td>
  </ng-container>

  <ng-container matColumnDef="Rank">
    <th mat-header-cell *matHeaderCellDef> Rank </th>
    <td mat-cell *matCellDef="let element"> {{element.Rank}} </td>
  </ng-container>

  <ng-container matColumnDef="PlayerName">
    <th mat-header-cell *matHeaderCellDef> Name </th>
    <td mat-cell *matCellDef="let element"> {{element.PlayerName}} </td>
  </ng-container>

  <ng-container matColumnDef="CountryName">
    <th mat-header-cell *matHeaderCellDef> Country </th>
    <td mat-cell *matCellDef="let element" title="{{element.CountryName}}"><img src="{{element.CountryImageLink}}"></td>
  </ng-container>

  <ng-container matColumnDef="Points">
    <th mat-header-cell *matHeaderCellDef> Points </th>
    <td mat-cell *matCellDef="let element"> {{element.Points}} </td>
  </ng-container>

  <ng-container matColumnDef="PrizeMoney">
    <th mat-header-cell *matHeaderCellDef> Prize Money </th>
    <td mat-cell *matCellDef="let element"> $ {{element.PrizeMoney}} </td>
  </ng-container>

  <ng-container matColumnDef="Action">
    <th mat-header-cell *matHeaderCellDef> Action </th>
    <td mat-cell *matCellDef="let element" class="action-link"> 
      <a href="#" (click)="openPlayerEditDialog('Update', element); $event.preventDefault();">Edit Player</a> 
      &nbsp;&nbsp;
      <a href="#" (click)="openRankingEditDialog('Update', element); $event.preventDefault();">Edit Ranking</a> 
    </td>
  </ng-container>


  <tr mat-header-row *matHeaderRowDef="rankingListColumns"></tr>
  <tr mat-row *matRowDef="let row; columns: rankingListColumns;"></tr>

</table>
