// AngularToGraphQL/src/app/player-list/player-list.component.ts
import { Component, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { PlayerViewService } from '../shared/player-view.service';
import { PlayerEditDialogComponent } from '../player/player-edit-dialog.component';

interface IdValue {
  id: string;
  value: string;
}

@Component({
  selector: 'player-list',
  templateUrl: './player-list.component.html',
  styles: [
    'table {      width: 100%;    }'
  ]
})
export class PlayerListComponent implements OnInit {

  playerList : any;
  playerListColumns : string[] = ['Name', 'Gender', 'Handed', 'Dob', 'Country', 'HomeTown','Action'];

  constructor(
    public playerViewService : PlayerViewService,
    public dialog: MatDialog
  ) { }

  ngOnInit(): void { 
    this.getPlayersCountryList(); 
  }

  refreshList() {
    this.getPlayersCountryList();
  }

  getPlayersCountryList() {
    this.playerViewService.getPlayersCountryList().subscribe(
      res => {
        this.playerList = res["players"];
      },
      err => {
        console.log(err);
      }
    );
  }

  openPlayerEditDialog(action, obj) {
    obj.action = action;
    obj.playerId = obj.id;
    const dialogRef = this.dialog.open(PlayerEditDialogComponent, {
      width: '500px',
      height: '550px',
      data: obj
    });
    
    dialogRef.afterClosed().subscribe(result => {
      this.refreshList();
    });
  }

  formatDateFromJson(jsonDate:string) {
    if (jsonDate == null || jsonDate.length < 10) {
      return "";
    }
    return jsonDate.substr(8, 2) + "/" + jsonDate.substr(5, 2) + "/" + jsonDate.substr(0, 4);
  }

}

Players

<table mat-table [dataSource]="playerList" class="mat-elevation-z8">
  <ng-container matColumnDef="Id">
    <th mat-header-cell *matHeaderCellDef> Id </th>
    <td mat-cell *matCellDef="let element"> {{element.id}} </td>
  </ng-container>

  <ng-container matColumnDef="Name">
    <th mat-header-cell *matHeaderCellDef> Name </th>
    <td mat-cell *matCellDef="let element"> {{element.name}} </td>
  </ng-container>

  <ng-container matColumnDef="Gender">
    <th mat-header-cell *matHeaderCellDef> Gender </th>
    <td mat-cell *matCellDef="let element"> {{element.gender}} </td>
  </ng-container>

  <ng-container matColumnDef="Handed">
    <th mat-header-cell *matHeaderCellDef> Handed </th>
    <td mat-cell *matCellDef="let element"> {{element.handed}} </td>
  </ng-container>

  <ng-container matColumnDef="Dob">
    <th mat-header-cell *matHeaderCellDef> Date of birth </th>
    <td mat-cell *matCellDef="let element"> {{formatDateFromJson(element.dob)}} </td>
  </ng-container>

  <ng-container matColumnDef="Country">
    <th mat-header-cell *matHeaderCellDef> Country </th>
    <td mat-cell *matCellDef="let element" title="{{element.country.name}}"><img src="{{element.country.imageLink}}"></td>
  </ng-container>

  <ng-container matColumnDef="HomeTown">
    <th mat-header-cell *matHeaderCellDef> Home town </th>
    <td mat-cell *matCellDef="let element"> {{element.homeTown}} </td>
  </ng-container>

  <ng-container matColumnDef="Action">
    <th mat-header-cell *matHeaderCellDef> Action </th>
    <td mat-cell *matCellDef="let element" class="action-link"> 
      <a href="#" (click)="openPlayerEditDialog('Update', element); $event.preventDefault();">Edit Player</a> 
    </td>
  </ng-container>


  <tr mat-header-row *matHeaderRowDef="playerListColumns"></tr>
  <tr mat-row *matRowDef="let row; columns: playerListColumns;"></tr>

</table>

// vuejs/src/components/PlayerList.vue
<template>
  <div>
    <div class="md-layout md-gutter">
      <div style="display:inline-block; font-size: 1.5em; margin-left: 1.0em; margin-top: 1.0em;">
      Players
      </div>
    </div>

    <md-table v-model="playersList" md-card md-sort="Name" md-sort-order="asc">
      <md-table-row slot="md-table-row" slot-scope="{ item }">
        <md-table-cell md-label="Name" class="left" md-sort-by="Name">{{ item.Name }}</md-table-cell>
        <md-table-cell md-label="Gender">{{ item.Gender }}</md-table-cell>
        <md-table-cell md-label="Handed">{{ item.Handed }}</md-table-cell>
        <md-table-cell md-label="Date of birth" md-sort-by="Dob">{{ item.Dob.substring(8,10) }}/{{ item.Dob.substring(5,7) }}/{{item.Dob.substring(0,4) }}</md-table-cell>
        <md-table-cell md-label="Country" :title="item.Country.Name"><img :src="item.Country.ImageLink"></md-table-cell>
        <md-table-cell md-label="Home town" class="left">{{ item.HomeTown }}</md-table-cell>
<!--        
        <md-table-cell md-label="Height">{{ item.HeightFeet }}' {{ item.HeightInches}} "</md-table-cell>
        <md-table-cell md-label="Weight">{{ item.Weight }} lbs</md-table-cell>
-->        
        <md-table-cell md-label="Actions" class="left">
          <a href="#" @click="openPlayerEditDialog(item.Id); $event.preventDefault();">Edit Player</a>
        </md-table-cell>
      </md-table-row>
    </md-table>
    <player-edit-dialog v-model="playerEditDialogOpen" :playerId="playerId"></player-edit-dialog>

  </div>
</template>

<script>
import DataMixin from "../mixins/data-mixin";
import PlayerEditDialog from "./PlayerEditDialog";

export default {
  name: 'PlayerList',
  components: {
    PlayerEditDialog
  },
  props: {
    msg: String
  },
  mixins: [DataMixin],
  data() {
    return {
      playerEditDialogOpen: false,
      playerId: 0,
    }
  },
  methods: {
    refreshList() {
      this.getPlayersList();
    },
    openPlayerEditDialog(playerId) {
      console.log("playerId=" + playerId);
      this.playerId = playerId;
      this.playerEditDialogOpen = false; // needed as need to trigger a change and sometimes value left at true
      this.playerEditDialogOpen = true;
    }

  },

  beforeMount() {
    this.getPlayersList();
  }  
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
<style>
.md-table-cell.left .md-table-cell-container {
  text-align: left !important;
}
</style>
