// reactjs/src/RankingList.js
import React, { useEffect } from 'react';

import './RankingList.css';
import InputLabel from '@material-ui/core/InputLabel';
import Select from '@material-ui/core/Select';
import MenuItem from '@material-ui/core/MenuItem';
import FormControl from '@material-ui/core/FormControl';
import { DataGrid } from '@material-ui/data-grid';

import PlayerEdit from './PlayerEdit';
import RankingEdit from './RankingEdit';

import { getRankingsList, getYears } from './DataService';


function RankingList() {

  const [gender, setGender] = React.useState('M');
  const [year, setYear] = React.useState(2021);
  const [years, setYears] = React.useState([]);
  const [rankings, setRankings] = React.useState([]);

  const selectGenderChange = (event) => {
    setGender(event.target.value);
  };

  const selectYearChange = (event) => {
    setYear(event.target.value);
  };

  const [selectedPlayerId, setSelectedPlayerId] = React.useState(0);
  const [selectedRankingId, setSelectedRankingId] = React.useState(0);

  const [playerEdit, setPlayerEdit] = React.useState(false);
  const editPlayer = (value) => {
    setSelectedPlayerId(value);
    fnPlayerEdit(true);
  };

  const fnPlayerEdit = (value) => {
    if (value !== undefined) {
      setPlayerEdit(value);
      return value;
    }
    return playerEdit;
  };

  const [rankingEdit, setRankingEdit] = React.useState(false);
  const editRanking = (value) => {
    setSelectedRankingId(value);
    fnRankingEdit(true);
  };

  const fnRankingEdit = (value) => {
    if (value !== undefined) {
      setRankingEdit(value);
      return value;
    }
    return rankingEdit;
  };

  const playerUpdated = () => {
    getRankings();
  };

  const rankingUpdated = () => {
    getRankings();
  };

  const genders = [
    {id: 'M', value: 'Men\'s'},
    {id: 'F', value: 'Women\'s'},
  ];

  const currencyFormatter = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
  });

  const columns = [
    { field: 'Rank', headerName: 'Rank', type: 'number', width: 100 },
    { field: 'PlayerName', headerName: 'Name', width: 160 },
    { field: 'CountryName', headerName: 'Country', width: 120, cellClassName: 'tableCellCentered',
      renderCell: (params) => (
        <img title={params.row.CountryName} src={params.row.CountryImageLink} alt={params.row.CountryName} className='flagCentered' />
      )
    },
    { field: 'Points', headerName: 'Points', type: 'number', width: 120 },
    { field: 'PrizeMoney', headerName: 'Prize Money', type: 'number', width: 160,
      valueFormatter: ({ value }) => currencyFormatter.format(Number(value)), },
    { field: 'PlayerId', headerName: 'Actions', width: 140,
      renderCell: (params) => (
        <button
          onClick={(e) => editPlayer(params.value)}
          className="buttonLink"
        >
          Edit Player
        </button>
      ),
    },
    { field: 'id', headerName: ' ', width: 140,
      renderCell: (params) => (
        <button
          onClick={(e) => editRanking(params.value)}
          className="buttonLink"
        >
          Edit Ranking
        </button>
      ),
    },
  
  ];

  useEffect(() => {
      getYears()
        .then(data => {
          setYears(data);
        });
    }, []
  );

  const getRankings = () => {
    getRankingsList(year, gender)
      .then(data => {
        data.forEach( rec => {
          rec.id = rec.Id;
          delete rec.Id;
        });
        console.log(data);
        setRankings(data);
      });
  };

  useEffect(() => {  
      getRankings();
// eslint-disable-next-line
    }, [gender, year]
  );

  return (
    <div>  
      <div className="title">
      Rankings
      </div>

      <FormControl className="formControlSelect">
      <InputLabel id="labelGender">Competition</InputLabel>
      <Select
        labelId="labelGender"
        id="selectGender"
        value={gender}
        onChange={selectGenderChange}
      >
        {genders.map(function(item, index){
          return <MenuItem value={item.id}>{item.value}</MenuItem>;
        })}
      </Select>
      </FormControl>


      <FormControl className="formControlSelect">
        <InputLabel id="labelYear">Year</InputLabel>
        <Select
          labelId="labelYear"
          id="selectYear"
          value={year}
          onChange={selectYearChange}
        >
          {years.map(function(item, index) {
            return <MenuItem value={item}>{item}</MenuItem>;
          })}
        </Select>
      </FormControl>
      <div style={{ height: 600, width: '100%' }}>
        <DataGrid rows={rankings} columns={columns} pageSize={8} 
        sortModel={[
          {
            field: 'Rank',
            sort: 'asc',
          },
        ]}
        />
      </div>
      <PlayerEdit requestOpen={fnPlayerEdit} playerId={selectedPlayerId} onUpdated={playerUpdated} />
      <RankingEdit requestOpen={fnRankingEdit} rankingId={selectedRankingId} onUpdated={rankingUpdated} />
    </div>
  );
}

export default RankingList;

// vuejs/src/components/RankingList.vue
<template>
  <div>
    <div class="md-layout md-gutter">
      <div style="display:inline-block; font-size: 1.5em; margin-left: 1.0em; margin-top: 1.0em;">
      Rankings
      </div>
      <div class="md-layout-item smaller-width">
        <md-field>
          <label for="selectGender">Competition </label>
          <md-select id="selectGender" v-model="selectedGender" @md-selected="refreshList" md-dense >
            <md-option v-for="gender in genders" :key="gender.id" :value="gender.id">{{gender.value}}</md-option>
          </md-select>
        </md-field>
      </div>  
      <div class="md-layout-item smaller-width">  
        <md-field>
          <label for="selectYear">Year </label>
          <md-select id="selectYear" v-model="selectedYear" @md-selected="refreshList" md-dense >
            <md-option v-for="year in years" :key="year" :value="year">{{year}}</md-option>
          </md-select>
        </md-field>
      </div>
    </div>

    <md-table v-model="rankingsList" md-card md-sort="Rank" md-sort-order="asc">
      <md-table-row slot="md-table-row" slot-scope="{ item }">
        <md-table-cell md-label="Rank" md-sort-by="Rank">{{ item.Rank }}</md-table-cell>
        <md-table-cell md-label="Player's Name">{{ item.PlayerName }}</md-table-cell>
        <md-table-cell md-label="Country" :title="item.CountryName"><img :src="item.CountryImageLink"></md-table-cell>
        <md-table-cell md-label="Points">{{ item.Points }}</md-table-cell>
        <md-table-cell md-label="Prize Money" md-sort-by="PrizeMoney">${{ item.PrizeMoney }}</md-table-cell>
        <md-table-cell md-label="Actions">
          <a href="#" @click="openPlayerEditDialog(item.PlayerId); $event.preventDefault();">Edit Player</a>
          <div style="display: inline-block; width: 15px;"> </div> 
          <a href="#" @click="openRankingEditDialog(item.Id); $event.preventDefault();">Edit Ranking</a>
        </md-table-cell>
      </md-table-row>
    </md-table>
    <player-edit-dialog v-model="playerEditDialogOpen" :playerId="playerId"></player-edit-dialog>
    <ranking-edit-dialog v-model="rankingEditDialogOpen" :rankingId="rankingId"></ranking-edit-dialog>
<!--
    <div v-for="ranking in rankingsList" :key="ranking.Id">
      -{{ranking.PlayerName}}
    </div>
-->    
  </div>
</template>

<script>
import DataMixin from "../mixins/data-mixin";
import PlayerEditDialog from "./PlayerEditDialog";
import RankingEditDialog from "./RankingEditDialog";
//import PlayerService from "../services/player-service";

//import { MdField, MdSelect, MdOption } from 'vue-material/dist/components';


export default {
  name: 'RankingList',
  components: {
    PlayerEditDialog,
    RankingEditDialog
  },
  props: [],
  mixins: [DataMixin],
  data() {
    return {
      selectedGender: '',
      selectedYear: '',
      genders: [
        {id: 'M', value: 'Men\'s'},
        {id: 'F', value: 'Women\'s'}
      ],
      playerEditDialogOpen: false,
      playerId: 0,
      rankingEditDialogOpen: false,
      rankingId: 0
    }
  },
  methods: {
    refreshList() {
      this.getRankingsList(this.selectedYear, this.selectedGender);
    },
    openPlayerEditDialog(playerId) {
      console.log("playerId=" + playerId);
      this.playerId = playerId;
      this.playerEditDialogOpen = false; // needed as need to trigger a change and sometimes value left at true
      this.playerEditDialogOpen = true;
    },
    openRankingEditDialog(rankingId) {
      console.log("rankingId=" + rankingId);
      this.rankingId = rankingId;
      this.rankingEditDialogOpen = false; // needed as need to trigger a change and sometimes value left at true
      this.rankingEditDialogOpen = true;
    }    

  },

  beforeMount() {
    this.selectedGender = this.genders[0].id;
    this.getYears().then(() => {
      this.selectedYear = this.years[1];
      this.getRankingsList(this.selectedYear, this.selectedGender);
    });   
  },

  mounted() {
  }

}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.smaller-width {
  max-width: 25%;
}

.md-table-cell {
  text-align: left;
}

h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
